version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: library-postgres
    environment:
      POSTGRES_DB: library_management_dev
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U library_user -d library_management_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: library-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://library_user:library_password@postgres:5432/library_management_dev?schema=public
      PORT: 3000
      LOG_LEVEL: info
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data:
